#the compose file version
version: "3.8"

services:

  webserver:
    image: nginx:stable-alpine
    container_name: module_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - module

  mysql:
    image: mysql:8.0.21
    container_name: module_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - mysql_master:/var/lib/mysql
      - mysql_master:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - module

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: module_PMA
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=${DB_HOST}
    networks:
      - module

  php:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: module_php
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "6001:6001" # ws port
    networks:
      - module

  #setup npm with node
  npm:
    image: node:14.9
    container_name: module_npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    container_name: module_redis
    volumes:
      - ./docker/redis:/var/www/html
    working_dir: /var/www/html
    networks:
      - module

networks:
  module:

volumes:
  mysql_master: